/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Affinity (
  nodeAffinity: Option[NodeAffinity] = None,
  podAffinity: Option[PodAffinity] = None,
  podAntiAffinity: Option[PodAntiAffinity] = None
) extends ApiModel


