/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Arguments (
  /* Artifacts is the list of artifacts to pass to the template or workflow */
  artifacts: Option[Seq[Artifact]] = None,
  /* Parameters is the list of parameters to pass to the template or workflow */
  parameters: Option[Seq[Parameter]] = None
) extends ApiModel


