/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Artifact (
  archive: Option[ArchiveStrategy] = None,
  /* ArchiveLogs indicates if the container logs should be archived */
  archiveLogs: Option[Boolean] = None,
  artifactory: Option[ArtifactoryArtifact] = None,
  /* From allows an artifact to reference an artifact from a previous step */
  from: Option[String] = None,
  gcs: Option[GCSArtifact] = None,
  git: Option[GitArtifact] = None,
  /* GlobalName exports an output artifact to the global scope, making it available as '{{outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts */
  globalName: Option[String] = None,
  hdfs: Option[HDFSArtifact] = None,
  http: Option[HTTPArtifact] = None,
  /* mode bits to use on this file, must be a value between 0 and 0777 set when loading input artifacts. */
  mode: Option[Int] = None,
  /* name of the artifact. must be unique within a template's inputs/outputs. */
  name: String,
  /* Make Artifacts optional, if Artifacts doesn't generate or exist */
  optional: Option[Boolean] = None,
  oss: Option[OSSArtifact] = None,
  /* Path is the container path to the artifact */
  path: Option[String] = None,
  raw: Option[RawArtifact] = None,
  s3: Option[S3Artifact] = None
) extends ApiModel


