/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class ArtifactLocation (
  /* ArchiveLogs indicates if the container logs should be archived */
  archiveLogs: Option[Boolean] = None,
  artifactory: Option[ArtifactoryArtifact] = None,
  gcs: Option[GCSArtifact] = None,
  git: Option[GitArtifact] = None,
  hdfs: Option[HDFSArtifact] = None,
  http: Option[HTTPArtifact] = None,
  oss: Option[OSSArtifact] = None,
  raw: Option[RawArtifact] = None,
  s3: Option[S3Artifact] = None
) extends ApiModel


