/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Backoff (
  /* Duration is the amount to back off. Default unit is seconds, but could also be a duration (e.g. \"2m\", \"1h\") */
  duration: Option[String] = None,
  /* Factor is a factor to multiply the base duration after each failed retry */
  factor: Option[Int] = None,
  /* MaxDuration is the maximum amount of time allowed for the backoff strategy */
  maxDuration: Option[String] = None
) extends ApiModel


