/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Capabilities (
  /* Added capabilities */
  add: Option[Seq[String]] = None,
  /* Removed capabilities */
  drop: Option[Seq[String]] = None
) extends ApiModel


