/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Condition (
  /* Message is the condition message */
  message: Option[String] = None,
  /* Status is the status of the condition */
  status: Option[String] = None,
  /* Type is the type of condition */
  `type`: Option[String] = None
) extends ApiModel


