/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class CronWorkflowSpec (
  /* ConcurrencyPolicy is the K8s-style concurrency policy that will be used */
  concurrencyPolicy: Option[String] = None,
  /* FailedJobsHistoryLimit is the number of successful jobs to be kept at a time */
  failedJobsHistoryLimit: Option[Int] = None,
  /* Schedule is a schedule to run the Workflow in Cron format */
  schedule: String,
  /* StartingDeadlineSeconds is the K8s-style deadline that will limit the time a CronWorkflow will be run after its original scheduled time if it is missed. */
  startingDeadlineSeconds: Option[Long] = None,
  /* SuccessfulJobsHistoryLimit is the number of successful jobs to be kept at a time */
  successfulJobsHistoryLimit: Option[Int] = None,
  /* Suspend is a flag that will stop new CronWorkflows from running if set to true */
  suspend: Option[Boolean] = None,
  /* Timezone is the timezone against which the cron schedule will be calculated, e.g. \"Asia/Tokyo\". Default is machine's local time. */
  timezone: Option[String] = None,
  workflowMetadata: Option[ObjectMeta] = None,
  workflowSpec: WorkflowSpec
) extends ApiModel


