/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class EnvFromSource (
  configMapRef: Option[ConfigMapEnvSource] = None,
  /* An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER. */
  prefix: Option[String] = None,
  secretRef: Option[SecretEnvSource] = None
) extends ApiModel


