/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class EnvVarSource (
  configMapKeyRef: Option[ConfigMapKeySelector] = None,
  fieldRef: Option[ObjectFieldSelector] = None,
  resourceFieldRef: Option[ResourceFieldSelector] = None,
  secretKeyRef: Option[SecretKeySelector] = None
) extends ApiModel


