/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class GitArtifact (
  /* Depth specifies clones/fetches should be shallow and include the given number of commits from the branch tip */
  depth: Option[Long] = None,
  /* Fetch specifies a number of refs that should be fetched before checkout */
  fetch: Option[Seq[String]] = None,
  /* InsecureIgnoreHostKey disables SSH strict host key checking during git clone */
  insecureIgnoreHostKey: Option[Boolean] = None,
  passwordSecret: Option[SecretKeySelector] = None,
  /* Repo is the git repository */
  repo: String,
  /* Revision is the git commit, tag, branch to checkout */
  revision: Option[String] = None,
  sshPrivateKeySecret: Option[SecretKeySelector] = None,
  usernameSecret: Option[SecretKeySelector] = None
) extends ApiModel


