/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class HDFSArtifact (
  /* Addresses is accessible addresses of HDFS name nodes */
  addresses: Seq[String],
  /* Force copies a file forcibly even if it exists (default: false) */
  force: Option[Boolean] = None,
  /* HDFSUser is the user to access HDFS file system. It is ignored if either ccache or keytab is used. */
  hdfsUser: Option[String] = None,
  krbCCacheSecret: Option[SecretKeySelector] = None,
  krbConfigConfigMap: Option[ConfigMapKeySelector] = None,
  krbKeytabSecret: Option[SecretKeySelector] = None,
  /* KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used. */
  krbRealm: Option[String] = None,
  /* KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used. */
  krbServicePrincipalName: Option[String] = None,
  /* KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used. */
  krbUsername: Option[String] = None,
  /* Path is a file path in HDFS */
  path: String
) extends ApiModel


