/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class HostAlias (
  /* Hostnames for the above IP address. */
  hostnames: Option[Seq[String]] = None,
  /* IP address of the host file entry. */
  ip: Option[String] = None
) extends ApiModel


