/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Inputs (
  /* Artifact are a list of artifacts passed as inputs */
  artifacts: Option[Seq[Artifact]] = None,
  /* Parameters are a list of parameters passed as inputs */
  parameters: Option[Seq[Parameter]] = None
) extends ApiModel


