/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class LabelSelector (
  /* matchExpressions is a list of label selector requirements. The requirements are ANDed. */
  matchExpressions: Option[Seq[LabelSelectorRequirement]] = None,
  /* matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed. */
  matchLabels: Option[Map[String, String]] = None
) extends ApiModel


