/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Link (
  /* The name of the link, E.g. \"Workflow Logs\" or \"Pod Logs\" */
  name: String,
  /* Either \"workflow\" or \"pod\" */
  scope: String,
  /* The URL. May contain \"${metadata.namespace}\" and \"${metadata.name}\". */
  url: String
) extends ApiModel


