/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class NodeSelectorTerm (
  /* A list of node selector requirements by node's labels. */
  matchExpressions: Option[Seq[NodeSelectorRequirement]] = None,
  /* A list of node selector requirements by node's fields. */
  matchFields: Option[Seq[NodeSelectorRequirement]] = None
) extends ApiModel


