/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class OSSArtifact (
  accessKeySecret: SecretKeySelector,
  /* Bucket is the name of the bucket */
  bucket: String,
  /* Endpoint is the hostname of the bucket endpoint */
  endpoint: String,
  /* Key is the path in the bucket where the artifact resides */
  key: String,
  secretKeySecret: SecretKeySelector
) extends ApiModel


