/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Outputs (
  /* Artifacts holds the list of output artifacts produced by a step */
  artifacts: Option[Seq[Artifact]] = None,
  /* ExitCode holds the exit code of a script template */
  exitCode: Option[String] = None,
  /* Parameters holds the list of output parameters produced by a step */
  parameters: Option[Seq[Parameter]] = None,
  /* Result holds the result (stdout) of a script template */
  result: Option[String] = None
) extends ApiModel


