/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class OwnerReference (
  /* API version of the referent. */
  apiVersion: String,
  /* If true, AND if the owner has the \"foregroundDeletion\" finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \"delete\" permission of the owner, otherwise 422 (Unprocessable Entity) will be returned. */
  blockOwnerDeletion: Option[Boolean] = None,
  /* If true, this reference points to the managing controller. */
  controller: Option[Boolean] = None,
  /* Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds */
  kind: String,
  /* Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names */
  name: String,
  /* UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids */
  uid: String
) extends ApiModel


