/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Parameter (
  /* Default is the default value to use for an input parameter if a value was not supplied DEPRECATED: This field is not used */
  default: Option[String] = None,
  /* GlobalName exports an output parameter to the global scope, making it available as '{{outputs.parameters.XXXX}} and in workflow.status.outputs.parameters */
  globalName: Option[String] = None,
  /* Name is the parameter name */
  name: String,
  /* Value is the literal value to use for the parameter. If specified in the context of an input parameter, the value takes precedence over any passed values */
  value: Option[String] = None,
  valueFrom: Option[ValueFrom] = None
) extends ApiModel


