/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import java.time.OffsetDateTime
import io.argoproj.workflow.ApiModel

case class PersistentVolumeClaimCondition (
  /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
  lastProbeTime: Option[OffsetDateTime] = None,
  /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
  lastTransitionTime: Option[OffsetDateTime] = None,
  /* Human-readable message indicating details about last transition. */
  message: Option[String] = None,
  /* Unique, this should be a short, machine understandable string that gives the reason for condition's last transition. If it reports \"ResizeStarted\" that means the underlying persistent volume is being resized. */
  reason: Option[String] = None,
  status: String,
  `type`: String
) extends ApiModel


