/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class PersistentVolumeClaimStatus (
  /* AccessModes contains the actual access modes the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 */
  accessModes: Option[Seq[String]] = None,
  /* Represents the actual resources of the underlying volume. */
  capacity: Option[Map[String, String]] = None,
  /* Current Condition of persistent volume claim. If underlying persistent volume is being resized then the Condition will be set to 'ResizeStarted'. */
  conditions: Option[Seq[PersistentVolumeClaimCondition]] = None,
  /* Phase represents the current phase of PersistentVolumeClaim. */
  phase: Option[String] = None
) extends ApiModel


