/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class PersistentVolumeClaimSpec (
  /* AccessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 */
  accessModes: Option[Seq[String]] = None,
  dataSource: Option[TypedLocalObjectReference] = None,
  resources: Option[ResourceRequirements] = None,
  selector: Option[LabelSelector] = None,
  /* Name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1 */
  storageClassName: Option[String] = None,
  /* volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec. This is a beta feature. */
  volumeMode: Option[String] = None,
  /* VolumeName is the binding reference to the PersistentVolume backing this claim. */
  volumeName: Option[String] = None
) extends ApiModel


