/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class PreferredSchedulingTerm (
  preference: NodeSelectorTerm,
  /* Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100. */
  weight: Int
) extends ApiModel


