/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Prometheus (
  counter: Counter,
  gauge: Gauge,
  /* Help is a string that describes the metric */
  help: String,
  histogram: Histogram,
  /* Labels is a list of metric labels */
  labels: Seq[MetricLabel],
  /* Name is the name of the metric */
  name: String,
  /* When is a conditional statement that decides when to emit the metric */
  when: String
) extends ApiModel


