/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class QuobyteVolumeSource (
  /* Group to map volume access to Default is no group */
  group: Option[String] = None,
  /* ReadOnly here will force the Quobyte volume to be mounted with read-only permissions. Defaults to false. */
  readOnly: Option[Boolean] = None,
  /* Registry represents a single or multiple Quobyte Registry services specified as a string as host:port pair (multiple entries are separated with commas) which acts as the central registry for volumes */
  registry: String,
  /* Tenant owning the given Quobyte volume in the Backend Used with dynamically provisioned Quobyte volumes, value is set by the plugin */
  tenant: Option[String] = None,
  /* User to map volume access to Defaults to serivceaccount user */
  user: Option[String] = None,
  /* Volume is a string that references an already created Quobyte volume by name. */
  volume: String
) extends ApiModel


