/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class ResourceTemplate (
  /* Action is the action to perform to the resource. Must be one of: get, create, apply, delete, replace, patch */
  action: String,
  /* FailureCondition is a label selector expression which describes the conditions of the k8s resource in which the step was considered failed */
  failureCondition: Option[String] = None,
  /* Flags is a set of additional options passed to kubectl before submitting a resource I.e. to disable resource validation: flags: [  \"--validate=false\"  # disable resource validation ] */
  flags: Option[Seq[String]] = None,
  /* Manifest contains the kubernetes manifest */
  manifest: String,
  /* MergeStrategy is the strategy used to merge a patch. It defaults to \"strategic\" Must be one of: strategic, merge, json */
  mergeStrategy: Option[String] = None,
  /* SetOwnerReference sets the reference to the workflow on the OwnerReference of generated resource. */
  setOwnerReference: Option[Boolean] = None,
  /* SuccessCondition is a label selector expression which describes the conditions of the k8s resource in which it is acceptable to proceed to the following step */
  successCondition: Option[String] = None
) extends ApiModel


