/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class S3Artifact (
  accessKeySecret: SecretKeySelector,
  /* Bucket is the name of the bucket */
  bucket: String,
  /* Endpoint is the hostname of the bucket endpoint */
  endpoint: String,
  /* Insecure will connect to the service with TLS */
  insecure: Option[Boolean] = None,
  /* Key is the key in the bucket where the artifact resides */
  key: String,
  /* Region contains the optional bucket region */
  region: Option[String] = None,
  /* RoleARN is the Amazon Resource Name (ARN) of the role to assume. */
  roleARN: Option[String] = None,
  secretKeySecret: SecretKeySelector,
  /* UseSDKCreds tells the driver to figure out credentials based on sdk defaults. */
  useSDKCreds: Option[Boolean] = None
) extends ApiModel


