/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class SELinuxOptions (
  /* Level is SELinux level label that applies to the container. */
  level: Option[String] = None,
  /* Role is a SELinux role label that applies to the container. */
  role: Option[String] = None,
  /* Type is a SELinux type label that applies to the container. */
  `type`: Option[String] = None,
  /* User is a SELinux user label that applies to the container. */
  user: Option[String] = None
) extends ApiModel


