/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Sequence (
  /* Count is number of elements in the sequence (default: 0). Not to be used with end */
  count: Option[String] = None,
  /* Number at which to end the sequence (default: 0). Not to be used with Count */
  end: Option[String] = None,
  /* Format is a printf format string to format the value in the sequence */
  format: Option[String] = None,
  /* Number at which to start the sequence (default: 0) */
  start: Option[String] = None
) extends ApiModel


