/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class StreamError (
  details: Option[Seq[Any]] = None,
  grpcCode: Option[Int] = None,
  httpCode: Option[Int] = None,
  httpStatus: Option[String] = None,
  message: Option[String] = None
) extends ApiModel


