/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class SubmitOpts (
  /* DryRun validates the workflow on the client-side without creating it. This option is not supported in API */
  dryRun: Option[Boolean] = None,
  /* Entrypoint overrides spec.entrypoint */
  entryPoint: Option[String] = None,
  /* GenerateName overrides metadata.generateName */
  generateName: Option[String] = None,
  /* Labels adds to metadata.labels */
  labels: Option[String] = None,
  /* Name overrides metadata.name */
  name: Option[String] = None,
  ownerReference: Option[OwnerReference] = None,
  /* ParameterFile holds a reference to a parameter file. This option is not supported in API */
  parameterFile: Option[String] = None,
  /* Parameters passes input parameters to workflow */
  parameters: Option[Seq[String]] = None,
  /* ServerDryRun validates the workflow on the server-side without creating it */
  serverDryRun: Option[Boolean] = None,
  /* ServiceAccount runs all pods in the workflow using specified ServiceAccount. */
  serviceAccount: Option[String] = None
) extends ApiModel


