/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class TarStrategy (
  /* CompressionLevel specifies the gzip compression level to use for the artifact. Defaults to gzip.DefaultCompression. */
  compressionLevel: Option[Int] = None
) extends ApiModel


