/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Template (
  /* Optional duration in seconds relative to the StartTime that the pod may be active on a node before the system actively tries to terminate the pod; value must be positive integer This field is only applicable to container and script templates. */
  activeDeadlineSeconds: Option[Long] = None,
  affinity: Option[Affinity] = None,
  archiveLocation: Option[ArtifactLocation] = None,
  arguments: Option[Arguments] = None,
  /* AutomountServiceAccountToken indicates whether a service account token should be automatically mounted in pods. ServiceAccountName of ExecutorConfig must be specified if this value is false. */
  automountServiceAccountToken: Option[Boolean] = None,
  container: Option[Container] = None,
  /* Deamon will allow a workflow to proceed to the next step so long as the container reaches readiness */
  daemon: Option[Boolean] = None,
  dag: Option[DAGTemplate] = None,
  executor: Option[ExecutorConfig] = None,
  /* HostAliases is an optional list of hosts and IPs that will be injected into the pod spec */
  hostAliases: Option[Seq[HostAlias]] = None,
  /* InitContainers is a list of containers which run before the main container. */
  initContainers: Option[Seq[UserContainer]] = None,
  inputs: Option[Inputs] = None,
  metadata: Option[Metadata] = None,
  metrics: Option[Metrics] = None,
  /* Name is the name of the template */
  name: String,
  /* NodeSelector is a selector to schedule this step of the workflow to be run on the selected node(s). Overrides the selector set at the workflow level. */
  nodeSelector: Option[Map[String, String]] = None,
  outputs: Option[Outputs] = None,
  /* Parallelism limits the max total parallel pods that can execute at the same time within the boundaries of this template invocation. If additional steps/dag templates are invoked, the pods created by those templates will not be counted towards this total. */
  parallelism: Option[Long] = None,
  /* PodSpecPatch holds strategic merge patch to apply against the pod spec. Allows parameterization of container fields which are not strings (e.g. resource limits). */
  podSpecPatch: Option[String] = None,
  /* Priority to apply to workflow pods. */
  priority: Option[Int] = None,
  /* PriorityClassName to apply to workflow pods. */
  priorityClassName: Option[String] = None,
  resource: Option[ResourceTemplate] = None,
  /* ResubmitPendingPods is a flag to enable resubmitting pods that remain Pending after initial submission */
  resubmitPendingPods: Option[Boolean] = None,
  retryStrategy: Option[RetryStrategy] = None,
  /* If specified, the pod will be dispatched by specified scheduler. Or it will be dispatched by workflow scope scheduler if specified. If neither specified, the pod will be dispatched by default scheduler. */
  schedulerName: Option[String] = None,
  script: Option[ScriptTemplate] = None,
  securityContext: Option[PodSecurityContext] = None,
  /* ServiceAccountName to apply to workflow pods */
  serviceAccountName: Option[String] = None,
  /* Sidecars is a list of containers which run alongside the main container Sidecars are automatically killed when the main container completes */
  sidecars: Option[Seq[UserContainer]] = None,
  /* Steps define a series of sequential/parallel workflow steps */
  steps: Option[Seq[Seq[WorkflowStep]]] = None,
  suspend: Option[SuspendTemplate] = None,
  /* Template is the name of the template which is used as the base of this template. DEPRECATED: This field is not used. */
  template: Option[String] = None,
  templateRef: Option[TemplateRef] = None,
  /* Tolerations to apply to workflow pods. */
  tolerations: Option[Seq[Toleration]] = None,
  /* Volumes is a list of volumes that can be mounted by containers in a template. */
  volumes: Option[Seq[Volume]] = None
) extends ApiModel


