/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class TTLStrategy (
  /* SecondsAfterCompletion is the number of seconds to live after completion */
  secondsAfterCompletion: Option[Int] = None,
  /* SecondsAfterFailure is the number of seconds to live after failure */
  secondsAfterFailure: Option[Int] = None,
  /* SecondsAfterSuccess is the number of seconds to live after success */
  secondsAfterSuccess: Option[Int] = None
) extends ApiModel


