/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class ValueFrom (
  /* Default specifies a value to be used if retrieving the value from the specified source fails */
  default: Option[String] = None,
  /* JQFilter expression against the resource object in resource templates */
  jqFilter: Option[String] = None,
  /* JSONPath of a resource to retrieve an output parameter value from in resource templates */
  jsonPath: Option[String] = None,
  /* Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. '{{steps.mystep.outputs.myparam}}') */
  parameter: Option[String] = None,
  /* Path in the container to retrieve an output parameter value from in container templates */
  path: Option[String] = None
) extends ApiModel


