/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class Version (
  buildDate: String,
  compiler: String,
  gitCommit: String,
  gitTag: String,
  gitTreeState: String,
  goVersion: String,
  platform: String,
  version: String
) extends ApiModel


