/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class VolumeDevice (
  /* devicePath is the path inside of the container that the device will be mapped to. */
  devicePath: String,
  /* name must match the name of a persistentVolumeClaim in the pod */
  name: String
) extends ApiModel


