/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class VsphereVirtualDiskVolumeSource (
  /* Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. */
  fsType: Option[String] = None,
  /* Storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName. */
  storagePolicyID: Option[String] = None,
  /* Storage Policy Based Management (SPBM) profile name. */
  storagePolicyName: Option[String] = None,
  /* Path that identifies vSphere volume vmdk */
  volumePath: String
) extends ApiModel


