/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class WorkflowStep (
  arguments: Option[Arguments] = None,
  continueOn: Option[ContinueOn] = None,
  /* Name of the step */
  name: Option[String] = None,
  /* OnExit is a template reference which is invoked at the end of the template, irrespective of the success, failure, or error of the primary template. */
  onExit: Option[String] = None,
  /* Template is the name of the template to execute as the step */
  template: Option[String] = None,
  templateRef: Option[TemplateRef] = None,
  /* When is an expression in which the step should conditionally execute */
  when: Option[String] = None,
  /* WithItems expands a step into multiple parallel steps from the items in the list */
  withItems: Option[Seq[String]] = None,
  /* WithParam expands a step into multiple parallel steps from the value in the parameter, which is expected to be a JSON list. */
  withParam: Option[String] = None,
  withSequence: Option[Sequence] = None
) extends ApiModel


