/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import java.time.OffsetDateTime
import io.argoproj.workflow.ApiModel

case class WorkflowStatus (
  /* Compressed and base64 decoded Nodes map */
  compressedNodes: Option[String] = None,
  /* Conditions is a list of conditions the Workflow may have */
  conditions: Option[Seq[Condition]] = None,
  /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
  finishedAt: Option[OffsetDateTime] = None,
  /* A human readable message indicating details about why the workflow is in this condition. */
  message: Option[String] = None,
  /* Nodes is a mapping between a node ID and the node's status. */
  nodes: Option[Map[String, NodeStatus]] = None,
  /* Whether on not node status has been offloaded to a database. If exists, then Nodes and CompressedNodes will be empty. This will actually be populated with a hash of the offloaded data. */
  offloadNodeStatusVersion: Option[String] = None,
  outputs: Option[Outputs] = None,
  /* PersistentVolumeClaims tracks all PVCs that were created as part of the  The contents of this list are drained at the end of the workflow. */
  persistentVolumeClaims: Option[Seq[Volume]] = None,
  /* Phase a simple, high-level summary of where the workflow is in its lifecycle. */
  phase: Option[String] = None,
  /* ResourcesDuration is the total for the workflow */
  resourcesDuration: Option[Map[String, Long]] = None,
  /* Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers. */
  startedAt: Option[OffsetDateTime] = None,
  /* StoredTemplates is a mapping between a template ref and the node's status. */
  storedTemplates: Option[Map[String, Template]] = None,
  storedWorkflowTemplateSpec: Option[WorkflowSpec] = None
) extends ApiModel


