/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class WorkflowTemplateUpdateRequest (
  /* DEPRECATED: This field is ignored. */
  name: Option[String] = None,
  namespace: Option[String] = None,
  template: Option[WorkflowTemplate] = None
) extends ApiModel


