/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.models

import io.argoproj.workflow.ApiModel

case class WorkflowCreateRequest (
  createOptions: Option[CreateOptions] = None,
  /* This field is no longer used. */
  instanceID: Option[String] = None,
  namespace: Option[String] = None,
  serverDryRun: Option[Boolean] = None,
  workflow: Option[Workflow] = None
) extends ApiModel


