/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.apis

import io.argoproj.workflow.models.Workflow
import io.argoproj.workflow.models.WorkflowList
import io.argoproj.workflow._
import io.argoproj.workflow.CollectionFormats._
import io.argoproj.workflow.ApiKeyLocations._

object ArchivedWorkflowServiceApi {

  def apply(baseUrl: String = "http://localhost:2746") = new ArchivedWorkflowServiceApi(baseUrl)
}

class ArchivedWorkflowServiceApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : Any (A successful response.)
   * 
   * @param uid 
   */
  def deleteArchivedWorkflow(uid: String): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.DELETE, baseUrl, "/api/v1/archived-workflows/{uid}", "application/json")
      .withPathParam("uid", uid)
      .withSuccessResponse[Any](200)
      

  /**
   * Expected answers:
   *   code 200 : Workflow (A successful response.)
   * 
   * @param uid 
   */
  def getArchivedWorkflow(uid: String): ApiRequest[Workflow] =
    ApiRequest[Workflow](ApiMethods.GET, baseUrl, "/api/v1/archived-workflows/{uid}", "application/json")
      .withPathParam("uid", uid)
      .withSuccessResponse[Workflow](200)
      

  /**
   * Expected answers:
   *   code 200 : WorkflowList (A successful response.)
   * 
   * @param listOptionsLabelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything. +optional.
   * @param listOptionsFieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything. +optional.
   * @param listOptionsWatch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion. +optional.
   * @param listOptionsAllowWatchBookmarks allowWatchBookmarks requests watch events with type \"BOOKMARK\". Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server's discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is beta.  +optional
   * @param listOptionsResourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it's 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv. +optional.
   * @param listOptionsTimeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity. +optional.
   * @param listOptionsLimit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param listOptionsContinue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the \"next key\".  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   */
  def listArchivedWorkflows(listOptionsLabelSelector: Option[String] = None, listOptionsFieldSelector: Option[String] = None, listOptionsWatch: Option[Boolean] = None, listOptionsAllowWatchBookmarks: Option[Boolean] = None, listOptionsResourceVersion: Option[String] = None, listOptionsTimeoutSeconds: Option[String] = None, listOptionsLimit: Option[String] = None, listOptionsContinue: Option[String] = None): ApiRequest[WorkflowList] =
    ApiRequest[WorkflowList](ApiMethods.GET, baseUrl, "/api/v1/archived-workflows", "application/json")
      .withQueryParam("listOptions.labelSelector", listOptionsLabelSelector)
      .withQueryParam("listOptions.fieldSelector", listOptionsFieldSelector)
      .withQueryParam("listOptions.watch", listOptionsWatch)
      .withQueryParam("listOptions.allowWatchBookmarks", listOptionsAllowWatchBookmarks)
      .withQueryParam("listOptions.resourceVersion", listOptionsResourceVersion)
      .withQueryParam("listOptions.timeoutSeconds", listOptionsTimeoutSeconds)
      .withQueryParam("listOptions.limit", listOptionsLimit)
      .withQueryParam("listOptions.continue", listOptionsContinue)
      .withSuccessResponse[WorkflowList](200)
      



}

