/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.argoproj.workflow.apis

import io.argoproj.workflow.models.InfoResponse
import io.argoproj.workflow.models.Version
import io.argoproj.workflow._
import io.argoproj.workflow.CollectionFormats._
import io.argoproj.workflow.ApiKeyLocations._

object InfoServiceApi {

  def apply(baseUrl: String = "http://localhost:2746") = new InfoServiceApi(baseUrl)
}

class InfoServiceApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : InfoResponse (A successful response.)
   */
  def getInfo(): ApiRequest[InfoResponse] =
    ApiRequest[InfoResponse](ApiMethods.GET, baseUrl, "/api/v1/info", "application/json")
      .withSuccessResponse[InfoResponse](200)
      

  /**
   * Expected answers:
   *   code 200 : Version (A successful response.)
   */
  def getVersion(): ApiRequest[Version] =
    ApiRequest[Version](ApiMethods.GET, baseUrl, "/api/v1/version", "application/json")
      .withSuccessResponse[Version](200)
      



}

