/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Artifact (
  archive: Option[ArchiveStrategy] = None,
  artifactLocation: Option[ArtifactLocation] = None,
  from: Option[String] = None,
  globalName: Option[String] = None,
  /* mode bits to use on this file, must be a value between 0 and 0777 set when loading input artifacts. */
  mode: Option[Int] = None,
  /* name of the artifact. must be unique within a template's inputs/outputs. */
  name: Option[String] = None,
  optional: Option[Boolean] = None,
  path: Option[String] = None
) extends ApiModel


