/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ArtifactLocation (
  archiveLogs: Option[Boolean] = None,
  artifactory: Option[ArtifactoryArtifact] = None,
  gcs: Option[GCSArtifact] = None,
  git: Option[GitArtifact] = None,
  hdfs: Option[HDFSArtifact] = None,
  http: Option[HTTPArtifact] = None,
  oss: Option[OSSArtifact] = None,
  raw: Option[RawArtifact] = None,
  s3: Option[S3Artifact] = None
) extends ApiModel


