/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Container (
  args: Option[Seq[String]] = None,
  command: Option[Seq[String]] = None,
  env: Option[Seq[EnvVar]] = None,
  envFrom: Option[Seq[EnvFromSource]] = None,
  image: Option[String] = None,
  imagePullPolicy: Option[String] = None,
  lifecycle: Option[Lifecycle] = None,
  livenessProbe: Option[Probe] = None,
  /* Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated. */
  name: Option[String] = None,
  ports: Option[Seq[ContainerPort]] = None,
  readinessProbe: Option[Probe] = None,
  resources: Option[ResourceRequirements] = None,
  securityContext: Option[SecurityContext] = None,
  startupProbe: Option[Probe] = None,
  stdin: Option[Boolean] = None,
  stdinOnce: Option[Boolean] = None,
  terminationMessagePath: Option[String] = None,
  terminationMessagePolicy: Option[String] = None,
  tty: Option[Boolean] = None,
  volumeDevices: Option[Seq[VolumeDevice]] = None,
  volumeMounts: Option[Seq[VolumeMount]] = None,
  workingDir: Option[String] = None
) extends ApiModel


