/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContainerPort (
  /* Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536. */
  containerPort: Option[Int] = None,
  hostIP: Option[String] = None,
  hostPort: Option[Int] = None,
  name: Option[String] = None,
  protocol: Option[String] = None
) extends ApiModel


