/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class DAGTask (
  arguments: Option[Arguments] = None,
  continueOn: Option[ContinueOn] = None,
  dependencies: Option[Seq[String]] = None,
  name: Option[String] = None,
  /* OnExit is a template reference which is invoked at the end of the template, irrespective of the success, failure, or error of the primary template. */
  onExit: Option[String] = None,
  template: Option[String] = None,
  templateRef: Option[TemplateRef] = None,
  when: Option[String] = None,
  withItems: Option[Seq[Item]] = None,
  /* WithParam expands a task into multiple parallel tasks from the value in the parameter, which is expected to be a JSON list. */
  withParam: Option[String] = None,
  withSequence: Option[Sequence] = None
) extends ApiModel


