/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class FCVolumeSource (
  fsType: Option[String] = None,
  lun: Option[Int] = None,
  readOnly: Option[Boolean] = None,
  targetWWNs: Option[Seq[String]] = None,
  wwids: Option[Seq[String]] = None
) extends ApiModel


