/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GitArtifact (
  depth: Option[String] = None,
  fetch: Option[Seq[String]] = None,
  insecureIgnoreHostKey: Option[Boolean] = None,
  passwordSecret: Option[SecretKeySelector] = None,
  repo: Option[String] = None,
  revision: Option[String] = None,
  sshPrivateKeySecret: Option[SecretKeySelector] = None,
  usernameSecret: Option[SecretKeySelector] = None
) extends ApiModel


