/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class HDFSKrbConfig (
  krbCCacheSecret: Option[SecretKeySelector] = None,
  krbConfigConfigMap: Option[ConfigMapKeySelector] = None,
  krbKeytabSecret: Option[SecretKeySelector] = None,
  /* KrbRealm is the Kerberos realm used with Kerberos keytab It must be set if keytab is used. */
  krbRealm: Option[String] = None,
  /* KrbServicePrincipalName is the principal name of Kerberos service It must be set if either ccache or keytab is used. */
  krbServicePrincipalName: Option[String] = None,
  /* KrbUsername is the Kerberos username used with Kerberos keytab It must be set if keytab is used. */
  krbUsername: Option[String] = None
) extends ApiModel


