/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ISCSIVolumeSource (
  chapAuthDiscovery: Option[Boolean] = None,
  chapAuthSession: Option[Boolean] = None,
  fsType: Option[String] = None,
  initiatorName: Option[String] = None,
  /* Target iSCSI Qualified Name. */
  iqn: Option[String] = None,
  iscsiInterface: Option[String] = None,
  /* iSCSI Target Lun number. */
  lun: Option[Int] = None,
  portals: Option[Seq[String]] = None,
  readOnly: Option[Boolean] = None,
  secretRef: Option[LocalObjectReference] = None,
  /* iSCSI Target Portal. The Portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260). */
  targetPortal: Option[String] = None
) extends ApiModel


