/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Item (
  boolVal: Option[Boolean] = None,
  listVal: Option[Seq[ItemValue]] = None,
  mapVal: Option[Map[String, ItemValue]] = None,
  numVal: Option[String] = None,
  strVal: Option[String] = None,
  `type`: Option[String] = None
) extends ApiModel


