/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class NodeStatus (
  boundaryID: Option[String] = None,
  children: Option[Seq[String]] = None,
  daemoned: Option[Boolean] = None,
  displayName: Option[String] = None,
  finishedAt: Option[Time] = None,
  id: Option[String] = None,
  inputs: Option[Inputs] = None,
  /* A human readable message indicating details about why the node is in this condition. */
  message: Option[String] = None,
  name: Option[String] = None,
  /* OutboundNodes tracks the node IDs which are considered \"outbound\" nodes to a template invocation. For every invocation of a template, there are nodes which we considered as \"outbound\". Essentially, these are last nodes in the execution sequence to run, before the template is considered completed. These nodes are then connected as parents to a following step.  In the case of single pod steps (i.e. container, script, resource templates), this list will be nil since the pod itself is already considered the \"outbound\" node. In the case of DAGs, outbound nodes are the \"target\" tasks (tasks with no children). In the case of steps, outbound nodes are all the containers involved in the last step group. NOTE: since templates are composable, the list of outbound nodes are carried upwards when a DAG/steps template invokes another DAG/steps template. In other words, the outbound nodes of a template, will be a superset of the outbound nodes of its last children. */
  outboundNodes: Option[Seq[String]] = None,
  outputs: Option[Outputs] = None,
  /* Phase a simple, high-level summary of where the node is in its lifecycle. Can be used as a state machine. */
  phase: Option[String] = None,
  podIP: Option[String] = None,
  /* ResourcesDuration is indicative, but not accurate, resource duration. This is populated when the nodes completes. */
  resourcesDuration: Option[Map[String, String]] = None,
  startedAt: Option[Time] = None,
  /* StoredTemplateID is the ID of stored template. DEPRECATED: This value is not used anymore. */
  storedTemplateID: Option[String] = None,
  templateName: Option[String] = None,
  templateRef: Option[TemplateRef] = None,
  /* TemplateScope is the template scope in which the template of this node was retrieved. */
  templateScope: Option[String] = None,
  `type`: Option[String] = None,
  /* WorkflowTemplateName is the WorkflowTemplate resource name on which the resolved template of this node is retrieved. DEPRECATED: This value is not used anymore. */
  workflowTemplateName: Option[String] = None
) extends ApiModel


