/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class OwnerReference (
  /* API version of the referent. */
  apiVersion: Option[String] = None,
  blockOwnerDeletion: Option[Boolean] = None,
  controller: Option[Boolean] = None,
  kind: Option[String] = None,
  name: Option[String] = None,
  uid: Option[String] = None
) extends ApiModel


