/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PodSecurityContext (
  /* 1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR'd with rw-rw----  If unset, the Kubelet will not modify the ownership and permissions of any volume. +optional */
  fsGroup: Option[String] = None,
  runAsGroup: Option[String] = None,
  runAsNonRoot: Option[Boolean] = None,
  runAsUser: Option[String] = None,
  seLinuxOptions: Option[SELinuxOptions] = None,
  supplementalGroups: Option[Seq[String]] = None,
  sysctls: Option[Seq[Sysctl]] = None,
  windowsOptions: Option[WindowsSecurityContextOptions] = None
) extends ApiModel


