/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PreferredSchedulingTerm (
  preference: Option[NodeSelectorTerm] = None,
  /* Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100. */
  weight: Option[Int] = None
) extends ApiModel


