/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ResourceTemplate (
  action: Option[String] = None,
  failureCondition: Option[String] = None,
  manifest: Option[String] = None,
  mergeStrategy: Option[String] = None,
  /* SetOwnerReference sets the reference to the workflow on the OwnerReference of generated resource. */
  setOwnerReference: Option[Boolean] = None,
  successCondition: Option[String] = None
) extends ApiModel


