/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ScaleIOVolumeSource (
  fsType: Option[String] = None,
  /* The host address of the ScaleIO API Gateway. */
  gateway: Option[String] = None,
  protectionDomain: Option[String] = None,
  readOnly: Option[Boolean] = None,
  secretRef: Option[LocalObjectReference] = None,
  sslEnabled: Option[Boolean] = None,
  storageMode: Option[String] = None,
  storagePool: Option[String] = None,
  /* The name of the storage system as configured in ScaleIO. */
  system: Option[String] = None,
  /* The name of a volume already created in the ScaleIO system that is associated with this volume source. */
  volumeName: Option[String] = None
) extends ApiModel


