/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class SecurityContext (
  allowPrivilegeEscalation: Option[Boolean] = None,
  capabilities: Option[Capabilities] = None,
  privileged: Option[Boolean] = None,
  procMount: Option[String] = None,
  readOnlyRootFilesystem: Option[Boolean] = None,
  runAsGroup: Option[String] = None,
  runAsNonRoot: Option[Boolean] = None,
  runAsUser: Option[String] = None,
  seLinuxOptions: Option[SELinuxOptions] = None,
  windowsOptions: Option[WindowsSecurityContextOptions] = None
) extends ApiModel


