/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class StorageOSVolumeSource (
  fsType: Option[String] = None,
  readOnly: Option[Boolean] = None,
  secretRef: Option[LocalObjectReference] = None,
  /* VolumeName is the human-readable name of the StorageOS volume.  Volume names are only unique within a namespace. */
  volumeName: Option[String] = None,
  volumeNamespace: Option[String] = None
) extends ApiModel


