/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TemplateRef (
  /* Name is the resource name of the template. */
  name: Option[String] = None,
  /* RuntimeResolution skips validation at creation time. By enabling this option, you can create the referred workflow template before the actual runtime. */
  runtimeResolution: Option[Boolean] = None,
  /* Template is the name of referred template in the resource. */
  template: Option[String] = None
) extends ApiModel


