/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class VolumeMount (
  /* Path within the container at which the volume should be mounted.  Must not contain ':'. */
  mountPath: Option[String] = None,
  mountPropagation: Option[String] = None,
  /* This must match the Name of a Volume. */
  name: Option[String] = None,
  readOnly: Option[Boolean] = None,
  subPath: Option[String] = None,
  subPathExpr: Option[String] = None
) extends ApiModel


