/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class WorkflowStatus (
  compressedNodes: Option[String] = None,
  conditions: Option[Seq[WorkflowCondition]] = None,
  finishedAt: Option[Time] = None,
  /* A human readable message indicating details about why the workflow is in this condition. */
  message: Option[String] = None,
  /* Nodes is a mapping between a node ID and the node's status. */
  nodes: Option[Map[String, NodeStatus]] = None,
  /* Whether on not node status has been offloaded to a database. If exists, then Nodes and CompressedNodes will be empty. This will actually be populated with a hash of the offloaded data. */
  offloadNodeStatusVersion: Option[String] = None,
  outputs: Option[Outputs] = None,
  /* PersistentVolumeClaims tracks all PVCs that were created as part of the  The contents of this list are drained at the end of the workflow. */
  persistentVolumeClaims: Option[Seq[Volume]] = None,
  /* Phase a simple, high-level summary of where the workflow is in its lifecycle. */
  phase: Option[String] = None,
  resourcesDuration: Option[Map[String, String]] = None,
  startedAt: Option[Time] = None,
  /* StoredTemplates is a mapping between a template ref and the node's status. */
  storedTemplates: Option[Map[String, Template]] = None
) extends ApiModel


