/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class WorkflowCreateRequest (
  createOptions: Option[CreateOptions] = None,
  instanceID: Option[String] = None,
  namespace: Option[String] = None,
  serverDryRun: Option[Boolean] = None,
  workflow: Option[Workflow] = None
) extends ApiModel


