/**
 * Argo
 * Argo
 *
 * The version of the OpenAPI document: v2.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.InfoResponse
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object InfoServiceApi {

  def apply(baseUrl: String = "http://localhost:2746") = new InfoServiceApi(baseUrl)
}

class InfoServiceApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : InfoResponse (A successful response.)
   */
  def getInfo(): ApiRequest[InfoResponse] =
    ApiRequest[InfoResponse](ApiMethods.GET, baseUrl, "/api/v1/info", "application/json")
      .withSuccessResponse[InfoResponse](200)
      



}

